### ISSUE TITLE
MIT License?!

### ISSUE THREAD

**Issue by Corniel** [pomma89/Troschuetz.Random#2]
I would like to use this library in a project that is under MIT. Do you think it would be feasible to change the license of Troschuetz.Random to MIT?

**Comment by pomma89** [comment]
Hi @Corniel,

I googled a bit in order to understand how your request should be properly handled. I found that the GTK project did the same you asked:

https://github.com/gtk-rs/gtk/issues/20

And what they did was to ask all project contributors if they wanted their work to be relicensed under the MIT license. Since this project has two recorded contributors, you and me, I formally ask you if you want to relicense your contribution under the MIT license.

For what concerns my contributions, I am more than willing to switch to the MIT license.

As soon as you acknowledge the relicense of your work, then I will proceed to change the project license.

Thank you.

**Comment by Corniel** [comment]
Yes, I'm fine with relicensing my contributions to MIT. :)

**Comment by pomma89** [comment]
Relicensed to MIT.
